# As a workaround to the issue in Nutika's implicit import detection
# explicitly import everything in the module recursively

import av
import av._core
import av.about
import av.audio
import av.audio.codeccontext
import av.audio.fifo
import av.audio.format
import av.audio.frame
import av.audio.layout
import av.audio.plane
import av.audio.resampler
import av.audio.stream
import av.buffer
import av.bytesource
import av.codec
import av.codec.codec
import av.codec.context
import av.container
import av.container.core
import av.container.input
import av.container.output
import av.container.pyio
import av.container.streams
import av.data
import av.data.stream
import av.datasets
import av.deprecation
import av.descriptor
import av.dictionary
import av.enum
import av.error
import av.filter
import av.filter.context
import av.filter.filter
import av.filter.graph
import av.filter.link
import av.filter.pad
import av.format
import av.frame
import av.logging
import av.option
import av.packet
import av.plane
import av.sidedata
import av.sidedata.motionvectors
import av.sidedata.sidedata
import av.stream
import av.subtitles
import av.subtitles.codeccontext
import av.subtitles.stream
import av.subtitles.subtitle
import av.utils
import av.video
import av.video.codeccontext
import av.video.format
import av.video.frame
import av.video.plane
import av.video.reformatter
import av.video.stream
